// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDds5VFOA9W3mJ-yB6W2Q3DVs6Bp3xcOkQ',
    appId: '1:828012214221:web:f775ea427ffcd3474e7684',
    messagingSenderId: '828012214221',
    projectId: 'first-flutter-project-a43b7',
    authDomain: 'first-flutter-project-a43b7.firebaseapp.com',
    storageBucket: 'first-flutter-project-a43b7.firebasestorage.app',
    measurementId: 'G-0N3D6WR006',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGhXZHX4B7jSISY7VQCPMc-gZOfJBt2U',
    appId: '1:828012214221:android:a86c908f8ce4b6864e7684',
    messagingSenderId: '828012214221',
    projectId: 'first-flutter-project-a43b7',
    storageBucket: 'first-flutter-project-a43b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVIXaGaL8Y5CO5QOIPFlkGwpODPHBnS1k',
    appId: '1:828012214221:ios:b8504436bb4da4884e7684',
    messagingSenderId: '828012214221',
    projectId: 'first-flutter-project-a43b7',
    storageBucket: 'first-flutter-project-a43b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVIXaGaL8Y5CO5QOIPFlkGwpODPHBnS1k',
    appId: '1:828012214221:ios:b8504436bb4da4884e7684',
    messagingSenderId: '828012214221',
    projectId: 'first-flutter-project-a43b7',
    storageBucket: 'first-flutter-project-a43b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDds5VFOA9W3mJ-yB6W2Q3DVs6Bp3xcOkQ',
    appId: '1:828012214221:web:2cdf33c5bfeb42804e7684',
    messagingSenderId: '828012214221',
    projectId: 'first-flutter-project-a43b7',
    authDomain: 'first-flutter-project-a43b7.firebaseapp.com',
    storageBucket: 'first-flutter-project-a43b7.firebasestorage.app',
    measurementId: 'G-0H3N4G5FFQ',
  );

}